In [9]:
import pandas as pd
import hvplot.pandas
import datetime as dt
import holoviews as hv

cpi_data=pd.read_csv('reformatted_cpi_data_daily.csv')
cpi_data.columns = ['Date', 'Data']
cpi_data['Date'] = pd.to_datetime(cpi_data['Date'])
cpi_data = cpi_data.set_index('Date')


#for asset in asset_list: 
  # Import the top 25 sp500 stocks dataset into a Pandas Dataframe
df = pd.read_csv('./asset_historical_prices/AAPL.csv', index_col='Date', infer_datetime_format=True, parse_dates=True)

#  (asset + ".csv"), 
#  index_col='Date', 
#  infer_datetime_format=True, 
#  parse_dates=True
#)

df = df.sort_values(by=['Date'], ascending = True)

#df = pd.concat([df1, cpi_data], axis=1)

# drop un-necessary columns
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df.drop(['Open', 'High', 'Low', 'Close', 'Volume'], axis=1, inplace=True)

df['CPI']=cpi_data['Data']

df = df.dropna()

# Reset the index so that we recode the columns for Prophet
df.reset_index()

df

             Adj Close      CPI
Date
2012-01-03   12.519281  226.665
2012-01-04   12.586559  226.665
2012-01-05   12.726291  226.665
2012-01-06   12.859332  226.665
2012-01-09   12.838936  226.665
...                ...      ...
2022-12-21  135.449997  298.300
2022-12-22  132.229996  298.300
2022-12-23  131.860001  298.300
2022-12-27  130.029999  298.300
2022-12-28  126.040001  298.300

[2766 rows x 2 columns]